### ISSUE TITLE
Can't find the generated pdf file

### ISSUE THREAD

**Issue by wenxiaofoo** [jrappen/sublime-wkhtmltopdf#2]
1. I download the wkhtmltopdf and install successfully at my laptop
2. I add the bin file to my PATH
3. install the plug-in package for sublime
4. write an html file and use wkhtmltopdf convert to pdf
5. nothing happened and I can't find the generated pdf

### Expected behavior

no idea

### Actual behavior

no idea

### Environment

```text
wkhtmltopdf:
    version: 0.12.5-1

wkhtmltopdf package:
    version: ?

Sublime Text:
    channel: stable
    version: 3176 (portable)
    platform: Windows
    architecture: x64
```

**Comment by jrappen** [comment]
The generated PDF files can be found in the same folder as the original HTML files.
